// Generated by CoffeeScript 1.12.7
(function() {
  var bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.PainlessGraph = (function() {
    function PainlessGraph(canvas) {
      this.canvas = canvas;
      console.log("constructed");
    }

    return PainlessGraph;

  })();

  window.PainlessSparql = (function() {
    function PainlessSparql(graph) {
      this.onkeypress_handler = bind(this.onkeypress_handler, this);
      this.graph = graph;
      this.cy = graph.cy;
      this.init();
    }

    PainlessSparql.prototype.init = function() {
      this.create_sidenav();
      return this.add_event_listener();
    };

    PainlessSparql.prototype.create_sidenav = function() {
      var side_nav, sparql_textbox;
      side_nav = document.createElement("div");
      side_nav.id = "sidenav";
      side_nav.className = "sidenav";
      side_nav.style.cssText = "height: 100%; width: 0%; position: fixed; z-index: 1; top: 0; right: 0; background-color: #111; overflow-x: hidden; padding-top: 60px; transition: 0.5s;";
      document.body.appendChild(side_nav);
      sparql_textbox = document.createElement("div");
      sparql_textbox.id = "sparql_textbox";
      sparql_textbox.innerHTML = "sparql_query_here";
      sparql_textbox.style.cssText = "color: blue";
      side_nav.appendChild(sparql_textbox);
      this.query_canvas = document.createElement("canvas");
      this.query_canvas.id = "query_canvas";
      side_nav.appendChild(this.query_canvas);
      return this.painless_graph = new PainlessGraph(this.query_canvas);
    };

    PainlessSparql.prototype.open_nav = function() {
      return document.getElementById("sidenav").style.width = "500px";
    };

    PainlessSparql.prototype.close_nav = function() {
      return document.getElementById("sidenav").style.width = "0px";
    };

    PainlessSparql.prototype.add_selected_node_to_sidenav = function() {
      var new_node_div, side_nav;
      side_nav = document.getElementById("sidenav");
      new_node_div = document.createElement("div");
      new_node_div.innerHTML = this.cy.$(":selected").data("label");
      return side_nav.append(new_node_div);
    };

    PainlessSparql.prototype.onkeypress_handler = function(event) {
      if (event.key === "a") {
        return this.open_nav();
      } else if (event.key === "b") {
        return this.close_nav();
      } else if (event.key === "c") {
        return this.add_selected_node_to_sidenav();
      }
    };

    PainlessSparql.prototype.add_event_listener = function() {
      return document.onkeypress = this.onkeypress_handler;
    };

    return PainlessSparql;

  })();

}).call(this);
