// Generated by CoffeeScript 1.12.7
(function() {
  var update_sparql_text;

  update_sparql_text = function() {
    var child, i, j, len, len1, parent, ref, ref1, sparql_string;
    sparql_string = "Select * <br> where { <br>";
    ref = cy.nodes(".node-variable");
    for (i = 0, len = ref.length; i < len; i++) {
      parent = ref[i];
      console.log("hey");
      ref1 = parent.neighborhood("node");
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        child = ref1[j];
        sparql_string += "&emsp;$" + parent.id() + " " + child.id() + "<br>";
      }
    }
    return sparql_text.innerHTML = sparql_string + "}";
  };

}).call(this);
